intro:
  steps:
    1:
      text: "这是改机情况记录页面，厂里叫外面师傅来改机的话，要记录。红色的为未结算尾款的记录，绿色为已结清的记录"
    2:
      title: "新建"
      text: "点击创建新的改机记录"
      attachTo:
        element: ".create_order"
        placement: "auto"
    3:
      title: "查询"
      text: "输入查询条件查找相关记录，例如改机人姓名、改机编号、机器针筒类型、目标型号等，"
      attachTo:
        element: "#search"
        placement: "auto"

