intro:
  steps:
    1:
      text: "供应商资料详情页面"
    2:
      title: "编辑"
      text: "供应商资料变更了？赶快更新吧"
      attachTo:
        element: ".edit_link"
        placement: "auto"
    3:
      title: "导出对账单"
      text: "供应商要对账了？点击将会导出所有已审核的交易来往，.xls格式"
      attachTo:
        element: ".export"
        placement: "auto"
