intro:
  steps:
    1:
      text: "采购单详情页面，原料采购后需要填的单子"
    2:
      title: "编辑"
      text: "单子上有内容错误？缺失？重新编辑吧！注意:作废的单据和通过审核的单据就无法修改了！"
      attachTo:
        element: ".edit_link"
        placement: "bottom"
    3:
      title: "通过审核"
      text: "您具有审核的权限,请确认单据内容正确后点击此按钮后，单据将记入系统计算。注意:已审核的单据无法编辑修改，如有错误只能作废后重新填写一张！"
      attachTo:
        element: ".pass_check_link"
        placement: "bottom"
    4:
      title: "作废"
      text: "单据错误？审核后不能修改了，那就只能作废再写一张了。"
      attachTo:
        element: ".destroy_link"
        placement: "bottom"